# fly.toml app configuration file generated for kumi-play-web on 2025-10-13T16:13:46-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kumi-play-web'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]
  [build.args]
    VITE_API_BASE = "https://kumi-play-web.fly.dev/"

[deploy]

[[mounts]]
  source = 'rails_storage'
  destination = '/rails/storage'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
